### ISSUE TITLE
relating haproxy with microsample unclear

### ISSUE THREAD

**Issue by EMCP** [erik78se/charm-microsample#2]
if I take a look at the haproxy charm, and how it requires/provides.. I can see it provides a website interface... but then so too does the microsample ??

![image](https://user-images.githubusercontent.com/3691722/84026456-a57ae900-a98d-11ea-8896-fee6475f9141.png)

If I have a server, hosting on port 9090... and I want to relate something else to it.. as of now I was under the assumption one `provides` and the other `requires` .. am I missing somewhere where the haproxy requires lines up with the micro sample ?

**Comment by erik78se** [comment]
Look closely at the haproxy charm as it has two possible relations implementing both of then the "http" interface. https://jaas.ai/haproxy/56

In the haproxy case, it implements the interface on both a "requires" basis and a "provides" basis.

You could have a look also at https://jaas.ai/ssl-termination-proxy which is another charm providing SSL/TLS capabilities.

**Comment by EMCP** [comment]
the image I pasted is that exact charms `metadata.yaml` because I couldn't see where the provides and requires lines up.. with this microsamples `provides`

```
name: haproxy
display-name: haproxy
summary: "fast and reliable load balancing reverse proxy"
maintainers: [Juan Negron <juan@ubuntu.com>, Tom Haddon <tom.haddon@canonical.com>]
description:
 HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high
 availability environments. It features connection persistence through HTTP
 cookies, load balancing, header addition, modification, deletion both ways. It
 has request blocking capabilities and provides interface to display server
 status.
tags: ["cache-proxy"]
series:
  - xenial
  - trusty
  - bionic
  - focal
requires:
  reverseproxy:
    interface: http
provides:
  website:
    interface: http
  munin:
    interface: munin-node
  nrpe-external-master:
    interface: nrpe-external-master
    scope: container
  local-monitors:
    interface: local-monitors
    scope: container
  statistics:
    interface: statistics
    scope: container
peers:
  peer:
    interface: haproxy-peer
extra-bindings:
  public:

```

unless the trick is, `reverseproxy` is connected to this charms `website` somehow when relating the two charms
